---
  - name: Ensure that php5-fpm is disabled
    become: True
    shell: systemctl stop php5-fpm && systemctl disable php5-fpm
    failed_when: False
    changed_when: False

  - name: Check if icingaweb-director is installed
    become: True
    stat: path=/usr/share/icingaweb2/modules/director
    register: icdstat

  - name: Download icingaweb-director (1.4)
    get_url: url="https://github.com/Icinga/icingaweb2-module-director/archive/v1.4.0.zip" dest="/tmp/icd.zip"
    when: not icdstat.stat.exists

  - name: Extract icingaweb-director
    become: True
    unarchive: src="/tmp/icd.zip" dest="/usr/share/icingaweb2/modules" remote_src=yes
    when: not icdstat.stat.exists

  - name: Rename icingaweb-director extracted dir...
    become: True
    shell: mv /usr/share/icingaweb2/modules/icingaweb2-module-director-1.4.0 /usr/share/icingaweb2/modules/director
    when: not icdstat.stat.exists

  - name: Create database for icingaweb
    become: True
    mysql_db: login_host="{{ mon_icinga_mysql_host }}" name={{ mon_icinga_mysql_web_database }} state=present
    tags: icdb

  - name: Create database for icingadirector
    become: True
    mysql_db: login_host="{{ mon_icinga_mysql_host }}" name={{ mon_icinga_mysql_director_database }} state=present encoding="utf8"
    register: ddbcreated
    tags: icdb

  - name: Import icingaweb director schema
    become: True
    mysql_db: login_host="{{ mon_icinga_mysql_host }}" name={{ mon_icinga_mysql_director_database }} state=import encoding="utf8" target="/usr/share/icingaweb2/modules/director/schema/mysql.sql"
    when: ddbcreated.changed
    tags: icdb

  - name: Create database user for icingaweb
    become: True
    mysql_user: login_host="{{ mon_icinga_mysql_host }}" name="{{ mon_icinga_mysql_web_user }}" password="{{ mon_icinga_mysql_web_password }}" priv="{{ mon_icinga_mysql_web_database }}.*:ALL"
    tags: icdb

  - name: Create database user for icingaweb-director
    become: True
    mysql_user: login_host="{{ mon_icinga_mysql_host }}" name="{{ mon_icinga_mysql_director_user }}" password="{{ mon_icinga_mysql_director_password }}" priv="{{ mon_icinga_mysql_director_database }}.*:ALL"
    tags: icdb

    # Per default, at least /etc/icingaweb2/modules has wrong ownership
  - name: Fix icingaweb directory ownership
    become: True
    file: path=/etc/icingaweb2 owner=www-data group=icingaweb2 recurse=yes
    tags: icconf

  - name: Create icinga nginx config file
    become: True
    template: src=nginx-dropin.conf.j2 dest=/etc/nginx/base.d/icinga.conf owner=root group=root mode=0644
    notify: restart nginx
    tags: icconf

  - name: Set php fpm default timezone
    become: True
    lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^date.timezone =' line='date.timezone = Europe/Zurich'
    notify: restart php-fpm

  - name: Ensure that the fpm/web user can access the icinga socket
    become: True
    user: name=www-data append=yes groups="icingaweb2"
    notify: restart php-fpm
