---
  - name: Ensure apache2 is not installed
    apt: name=apache2 state=absent

  - name: Prevent apache2 from being installed
    copy: src=noapache.conf dest=/etc/apt/preferences.d/noapache

  - name: Install additional icinga packages
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
    with_items:
      - icinga2-ido-mysql
      - icingaweb2
      - php5-fpm
      - php5-imagick
      - php5-intl

  - name: Concat CA and CRL
    assemble: src=/etc/icinga2/pki/ca dest=/etc/icinga2/pki/ca-mag.crt
    changed_when: False

  # Per default the socket is owned by nagios:www-run
  - name: Enable icinga modules
    command: icinga2 feature enable {{ item }} creates=/etc/icinga2/features-enabled/{{ item }}.conf
    notify: restart icinga
    with_items:
      - command
      - perfdata
      - graphite
      - ido-mysql
      - api

  - name: Create database for icinga
    mysql_db: login_host="{{ icinga_mysql_host }}" name=icinga state=present
    register: dbcreated

  - name: Create database for icingaweb
    mysql_db: login_host="{{ icinga_mysql_host }}" name=icingaweb state=present

  - name: Import icinga schema
    shell: mysql -h {{ icinga_mysql_host }} icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql
    when: dbcreated.changed

  - name: Create database user for icinga
    mysql_user: login_host="{{ icinga_mysql_host }}" name=icinga password="{{ icinga_mysql_password }}" priv="icinga.*:ALL"

  - name: Create database user for icingaweb
    mysql_user: login_host="{{ icinga_mysql_host }}" name=icingaweb password="{{ icinga_mysql_web_password }}" priv="icingaweb.*:ALL"

    # Per default, at least /etc/icingaweb2/modules has wrong ownership
  - name: Fix icingaweb directory ownership
    file: path=/etc/icingaweb2 owner=www-data group=icingaweb2 recurse=yes

  - name: Create icinga nginx config file
    template: src=nginx-dropin.conf.j2 dest=/etc/nginx/base.d/icinga.conf owner=root group=root mode=0644
    notify: restart nginx

  - name: Create icinga config files
    template: src={{item }}.j2 dest=/etc/icinga2/conf.d/{{item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - templates.conf
      - notifications.conf.j2
      - users.conf.j2

  - name: Create icinga main configs
    template: src={{ item }}.j2 dest=/etc/icinga2/{{ item }} owner=root group=root mode=0644
    notify: restart icinga
    with_items:
      - icinga2.conf
      - constants.conf
      - zones.conf

  - name: Configure icinga features
    template: src={{ item }}.j2 dest=/etc/icinga2/features-available/{{ item }} owner=root group=nagios mode=0640
    notify: restart icinga
    with_items:
      - graphite.conf
      - ido-mysql.conf
      - api.conf

  - name: Configure client hosts
    template: src=client-host.conf.j2 dest=/etc/icinga2/conf.d/cl-{{item}}.conf owner=root group=nagios mode=0640
    notify: restart icinga
    with_items: "{{ groups['mon-client'] }}"

  - name: Set php fpm default timezone
    lineinfile: dest=/etc/php5/fpm/php.ini regexp='^date.timezone =' line='date.timezone = Europe/Zurich'
    notify: restart php-fpm

  - name: Ensure that the fpm/web user can access the icinga socket
    user: name=www-data append=yes groups="icingaweb2"
    notify: restart php-fpm
