---
  - name: restart icinga
    service: name=icinga2 enabled=yes state=restarted

  - name: restart nginx
    service: name=nginx enabled=yes state=restarted

  - name: restart php-fpm
    service: name=php5-fpm enabled=yes state=restarted
